#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ProjectNMM.AndroidUI.Resource", IsApplication=true)]

namespace ProjectNMM.AndroidUI
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ProjectNMM.Model.Resource.String.library_name = global::ProjectNMM.AndroidUI.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int StartScreen_SpnGameMode_Entries = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060004
			public const int BtnAbout = 2131099652;
			
			// aapt resource value: 0x7f060002
			public const int BtnBack = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int BtnNewGame = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int BtnStartGame = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int LblLicense = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int LblProjectSite = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int LblTitle = 2131099653;
			
			// aapt resource value: 0x7f060008
			public const int SpnGameMode = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int TxtNamePlayer1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int TxtNamePlayer2 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainScreen = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int StartScreen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04000b
			public const int AboutScreen_BtnBack = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int MainScreen_BtnAbout = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int MainScreen_BtnNewGame = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int Menu_Action01 = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Menu_Action02 = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Menu_Title = 2130968578;
			
			// aapt resource value: 0x7f04000f
			public const int Playevent_CannotBreakMill = 2130968591;
			
			// aapt resource value: 0x7f040015
			public const int Playevent_CannotUndoMill = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int Playevent_FinishTurn = 2130968596;
			
			// aapt resource value: 0x7f040012
			public const int Playevent_GameOverNoMovesPossible = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Playevent_GameOverNoPlaystonesLeft = 2130968595;
			
			// aapt resource value: 0x7f040010
			public const int Playevent_InvalidPlaystone = 2130968592;
			
			// aapt resource value: 0x7f04000c
			public const int Playevent_NoEvent = 2130968588;
			
			// aapt resource value: 0x7f040011
			public const int Playevent_NoPlaystonesRemovable = 2130968593;
			
			// aapt resource value: 0x7f04000d
			public const int Playevent_PlayerHasMill = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int Playevent_WrongPlaystoneAfterMill = 2130968590;
			
			// aapt resource value: 0x7f04000a
			public const int StartScreen_BtnStartGame = 2130968586;
			
			// aapt resource value: 0x7f040007
			public const int StartScreen_Title = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int StartScreen_TxtNamePlayer1_Hint = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int StartScreen_TxtNamePlayer2_Hint = 2130968585;
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
